name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:  # https://github.com/actions/python-versions/releases
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: pip install --upgrade pip
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: pip install --editable . || true
      - run: pip install psutil
      - run: pytest
